table Calendar
	lineageTag: f6e78640-383c-40d3-bf96-c66fe86b0bc3

	column DateTime
		dataType: dateTime
		isNullable: false
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 5865330b-9fe8-40dc-a02f-2fd3113b14cb
		summarizeBy: none
		sourceColumn: DateTime

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Calendar","TableItemName":"DateTime(Hour)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Calendar","TableItemName":"DateTime(15min)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 577a0289-bbcf-4227-a53f-e60215ed2c42
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 2c9eed10-18d6-4ecc-9ceb-31bfdb202960
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 464f2f55-4115-47a4-9fe9-92c2af7b374e
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: bcc2383c-a7e9-42ef-a56c-d43314d91195
		summarizeBy: sum
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: b7e81c34-c483-49ce-9cd7-1d88f7f70b3d
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Minute
		dataType: int64
		formatString: 0
		lineageTag: 38931c98-8516-4d7f-a87b-e2bb69457c5d
		summarizeBy: sum
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column YYYYMMDD
		dataType: int64
		formatString: 0
		lineageTag: 21328973-b382-45c6-8952-348422e5cad7
		summarizeBy: sum
		sourceColumn: YYYYMMDD

		annotation SummarizationSetBy = Automatic

	column DateTime(Hour) =
			IF(
				ISBLANK('Calendar'[DateTime]),
				BLANK(),
				INT('Calendar'[DateTime] * 24) / 24
			)
		dataType: dateTime
		formatString: General Date
		lineageTag: c81795a9-a4f9-4f57-b72c-fde7b035fae5
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Calendar"
				          }
				        },
				        "Property": "DateTime"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 1.0,
				      "unit": 9
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"c","Entity":"Calendar"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"DateTime"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"DateTime"}},"Size":1.0,"TimeUnit":7}}}}

		annotation SummarizationSetBy = Automatic

	column DateTime(15min) =
			IF(
				ISBLANK('Calendar'[DateTime]),
				BLANK(),
				(INT(('Calendar'[DateTime] * 1440) / 15) * 15) / 1440
			)
		dataType: dateTime
		formatString: General Date
		lineageTag: 901a8409-dc87-44ff-af36-32c993c8f178
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Calendar"
				          }
				        },
				        "Property": "DateTime"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 15.0,
				      "unit": 10
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"c","Entity":"Calendar"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"DateTime"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"DateTime"}},"Size":15.0,"TimeUnit":6}}}}

		annotation SummarizationSetBy = Automatic

	partition Calendar-8d890e69-fd08-4de2-ad3b-8a3d1e0019e7 = m
		mode: import
		source =
				let
				    Start = Date.StartOfDay(if RangeStart is null then Date.AddDays(DateTime.FixedLocalNow(), -#"Days Ago To Start"-1) else RangeStart),
				    End = Date.StartOfDay(if RangeEnd is null then Date.AddDays(DateTime.FixedLocalNow(), -#"Days Ago To Finish"+2) else RangeEnd),
				    Count = (Number.From(End-Start))*2880,
				    Calendar = Table.FromColumns({List.DateTimes(DateTime.From(Start),Count,#duration(0,0,0,30))}, type table[DateTime=datetime]),
				    #"Inserted Date" = Table.AddColumn(Calendar, "Date", each DateTime.Date([DateTime]), type date),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Date", "Day", each Date.Day([DateTime]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([DateTime]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([DateTime]), Int64.Type),
				    #"Inserted Hour" = Table.AddColumn(#"Inserted Day of Week", "Hour", each Time.Hour([DateTime]), Int64.Type),
				    #"Inserted Minute" = Table.AddColumn(#"Inserted Hour", "Minute", each Time.Minute([DateTime]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Minute", "YYYYMMDD", each Date.ToText([Date], [Format="yyyyMMdd"])),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"YYYYMMDD", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

