table SizeUnits
	isHidden
	excludeFromModelRefresh
	lineageTag: ae2ac8d5-ebf2-4d22-9fd7-b007b8d770ba

	measure SelectedSizeUnit = SELECTEDVALUE(SizeUnits[UnitValueFromKB])
		isHidden
		lineageTag: 8af10c17-c58d-44c4-92de-a0945e005f61

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelectedSizeUnitName = SELECTEDVALUE(SizeUnits[UnitShort])
		lineageTag: 46dd46e1-2ef9-462d-bb82-8f8290c590cd

	column UnitKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 300587ec-18a5-4037-a232-2d636bb669d5
		summarizeBy: count
		sourceColumn: UnitKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		isHidden
		lineageTag: cd43cfc9-7e98-4b7d-a906-85633093bb54
		summarizeBy: none
		sourceColumn: Unit
		sortByColumn: UnitKey

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitValue
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 35fb0c35-db9c-4080-a611-3358df992364
		summarizeBy: sum
		sourceColumn: UnitValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitValueFromKB
		dataType: double
		isHidden
		lineageTag: bfaea6aa-2cd3-46b8-98a7-04a792ef74c3
		summarizeBy: sum
		sourceColumn: UnitValueFromKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitShort
		dataType: string
		isHidden
		lineageTag: a44c53ac-16ed-495e-841d-267f2adfa8a5
		summarizeBy: none
		sourceColumn: UnitShort
		sortByColumn: UnitKey

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition SizeUnits = m
		mode: import
		queryGroup: Units
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUUqqLEktBtIgtoGegYGBpbmZqZmRKZDrBJaK1YlWMgLysjNz8uGKDYxMoHq8ncAqjIHM3NT0RIQKEwtTczOEWl+IOhAzPRNZnbmxuYmhBcQ8uCZ3oOpYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [UnitKey = _t, Unit = _t, UnitValue = _t, UnitValueFromKB = _t, UnitShort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"UnitKey", Int64.Type}, {"Unit", type text}, {"UnitValue", Int64.Type}, {"UnitValueFromKB", type number}, {"UnitShort", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

