CREATE TABLE [dbo].[data_catalog] (

	[asset_id] varchar(8000) NULL, 
	[asset_name] varchar(8000) NULL, 
	[asset_type] varchar(8000) NULL, 
	[sector] varchar(8000) NULL, 
	[owner] varchar(8000) NULL, 
	[source_system] varchar(8000) NULL, 
	[layer] varchar(8000) NULL, 
	[status] varchar(8000) NULL, 
	[quality_score] float NULL, 
	[last_updated] date NULL, 
	[nb_rows] bigint NULL, 
	[nb_columns] int NULL, 
	[has_pii] bit NULL, 
	[classification] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[_bronze_ts] datetime2(6) NULL, 
	[_source_system] varchar(8000) NULL, 
	[_source_file] varchar(8000) NULL, 
	[_silver_hash] varchar(8000) NULL, 
	[_silver_ts] datetime2(6) NULL, 
	[avg_dq_score] float NULL, 
	[nb_checks] bigint NULL, 
	[nb_dq_failed] bigint NULL, 
	[last_dq_date] date NULL, 
	[dq_status] varchar(8000) NULL, 
	[_gold_ts] datetime2(6) NULL
);