CREATE TABLE [dbo].[gold_geomarketing_scoring] (

	[store_id] varchar(8000) NULL, 
	[ville] varchar(8000) NULL, 
	[population_primaire] int NULL, 
	[population_secondaire] int NULL, 
	[revenu_moyen_chf] int NULL, 
	[pct_familles] float NULL, 
	[pct_seniors] float NULL, 
	[pct_actifs] float NULL, 
	[indice_pouvoir_achat] float NULL, 
	[nb_concurrents_directs] int NULL, 
	[nb_concurrents_indirects] int NULL, 
	[part_de_marche_estimee_pct] float NULL, 
	[potentiel_ca_zone_mchf] float NULL, 
	[indice_attractivite] float NULL, 
	[flux_pietons_semaine] int NULL, 
	[accessibilite_score] float NULL, 
	[_bronze_ts] datetime2(6) NULL, 
	[_source_system] varchar(8000) NULL, 
	[_source_file] varchar(8000) NULL, 
	[_silver_hash] varchar(8000) NULL, 
	[_silver_ts] datetime2(6) NULL, 
	[nom] varchar(8000) NULL, 
	[format] varchar(8000) NULL, 
	[concept] varchar(8000) NULL, 
	[surface_m2] int NULL, 
	[statut] varchar(8000) NULL, 
	[latitude] float NULL, 
	[longitude] float NULL, 
	[ca_total_chf] float NULL, 
	[ca_moyen_hebdo] float NULL, 
	[taux_captation_pct] float NULL, 
	[score_potentiel_implantation] float NULL, 
	[recommandation] varchar(8000) NULL, 
	[_gold_ts] datetime2(6) NULL
);